version: 2
jobs:
  test:
    docker:
      - image: java:openjdk-8-jre-alpine
    steps:
      - run: apk add --update git openssh
      - checkout
      - run: apk add --update nodejs wget bash python make g++ java-cacerts ttf-dejavu fontconfig && npm install -g yarn && ln -sf "${JAVA_HOME}/bin/"* "/usr/bin/"
      - run: wget -O /usr/local/bin/lein https://raw.github.com/technomancy/leiningen/stable/bin/lein && chmod +x /usr/local/bin/lein
      - run: ./bin/ci

  build:
    docker:
      - image: java:openjdk-8-jre-alpine
    steps:
      - run: apk add --update git openssh
      - checkout
      - run: apk add --update nodejs wget bash python make g++ java-cacerts ttf-dejavu fontconfig && npm install -g yarn && ln -sf "${JAVA_HOME}/bin/"* "/usr/bin/"
      - run: wget -O /usr/local/bin/lein https://raw.github.com/technomancy/leiningen/stable/bin/lein && chmod +x /usr/local/bin/lein
      - run: ./bin/build
      - persist_to_workspace:
          root: target
          paths:
            - uberjar/metabase.jar

  release:
    environment:
      SERVICE: metabase
    docker:
      - image: ${STAGING_ECR_URL}/docker-deploy
        aws_auth: &ecr_credentials
          aws_access_key_id: $STAGING_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $STAGING_AWS_SECRET_ACCESS_KEY
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Move jar
          command: |
            cp /tmp/workspace/uberjar/metabase.jar bin/docker/
            cd bin/docker
      - run:
          name: Build application docker image
          command: |
            docker build -t ${STAGING_ECR_URL}/${SERVICE}:${CIRCLE_SHA1} .
      - run:
          name: Push image
          command: |
            ENVIRONMENT=staging DOCKER_IMAGE="${STAGING_ECR_URL}/${SERVICE}" TAG=${CIRCLE_SHA1} /docker-push.sh

workflows:
  version: 2
  test:
    jobs:
      - test:
          context: org-global
      - build:
          context: org-global
          requires:
            - test
      - release:
          context: org-global
          requires:
            - build
