version: 2
jobs:
  test:
    docker:
      - image: java:openjdk-8-jre-alpine
    steps:
      - run: apk add --update git openssh
      - checkout
      - run: apk add --update nodejs wget bash python make g++ java-cacerts ttf-dejavu fontconfig && npm install -g yarn && ln -sf "${JAVA_HOME}/bin/"* "/usr/bin/"
      - run: wget -O /usr/local/bin/lein https://raw.github.com/technomancy/leiningen/stable/bin/lein && chmod +x /usr/local/bin/lein
      - run: ./bin/ci

  build:
    docker:
      - image: java:openjdk-8-jre-alpine
    steps:
      - run: apk add --update git openssh
      - checkout
      - run: apk add --update nodejs wget bash python make g++ java-cacerts ttf-dejavu fontconfig && npm install -g yarn && ln -sf "${JAVA_HOME}/bin/"* "/usr/bin/"
      - run: wget -O /usr/local/bin/lein https://raw.github.com/technomancy/leiningen/stable/bin/lein && chmod +x /usr/local/bin/lein
      - run: ./bin/build
      - persist_to_workspace:
          root: target
          paths:
            - uberjar/metabase.jar

workflows:
  version: 2
  test:
    jobs:
      - test:
          context: org-global
      - build:
          context: org-global
          requires:
            - test
