version: 2
jobs:
  test:
    docker:
      - image: java:openjdk-8-jre-alpine
    steps:
      - checkout
      - run: apk add --update nodejs git wget bash python make g++ java-cacerts ttf-dejavu fontconfig && npm install -g yarn && ln -sf "${JAVA_HOME}/bin/"* "/usr/bin/"
      - run: wget -O /usr/local/bin/lein https://raw.github.com/technomancy/leiningen/stable/bin/lein && chmod +x /usr/local/bin/lein
      - run: ./bin/ci

workflows:
  version: 2
  test:
    jobs:
      - test:
          context: org-global
